// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onLiftChange();
void onMoveChange();

CloudDimmedLight lift;
CloudDimmedLight move;

void initProperties(){

  ArduinoCloud.addProperty(lift, READWRITE, ON_CHANGE, onLiftChange);
  ArduinoCloud.addProperty(move, READWRITE, ON_CHANGE, onMoveChange);
  

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
